# Generated by Django 2.2.2 on 2019-06-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOURINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('dailyTravelTime', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('finished', models.IntegerField(default=0)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.GROUP')),
                ('guideID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.GUIDE')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.USER')),
            ],
        ),
        migrations.CreateModel(
            name='USERGROUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.GROUP')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.USER')),
            ],
        ),
        migrations.CreateModel(
            name='TOURISTSPOTPREFERENCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='allImages/')),
                ('preferenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.PREFERENCE')),
                ('spotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURISTSPOT')),
            ],
        ),
        migrations.CreateModel(
            name='TOURINFOTOURISTSPOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURISTSPOT')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='TOURINFOPREFERENCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.PREFERENCE')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='TOURINFOGROUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.GROUP')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='TOURINFOACTIVITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.ACTIVITY')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='SPOTACTIVITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='allImages/')),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.ACTIVITY')),
                ('spotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURISTSPOT')),
            ],
        ),
        migrations.CreateModel(
            name='PREFERENCETOURINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.PREFERENCE')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='HOTELTOURINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.HOTEL')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='GUIDETOURINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.GUIDE')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='CITYTOURINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CITY')),
                ('tourID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TOURINFO')),
            ],
        ),
        migrations.CreateModel(
            name='CITYPREFERENCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CITY')),
                ('preferenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.PREFERENCE')),
            ],
        ),
        migrations.CreateModel(
            name='CITYGUIDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CITY')),
                ('guideID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.GUIDE')),
            ],
        ),
    ]
