# Generated by Django 2.2.2 on 2019-06-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_cityguide_citypreference_citytourinfo_guidetourinfo_hoteltourinfo_preferencetourinfo_spotactivity_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activityImages',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='preferenceImages',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='preferenceNanme',
            new_name='preferenceName',
        ),
        migrations.RenameField(
            model_name='touristspot',
            old_name='touristSpotImages',
            new_name='image',
        ),
    ]
