# Generated by Django 2.2.2 on 2019-06-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20190614_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='allImages/'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='allImages/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='allImages/'),
        ),
    ]
